require: rubocop-rspec

AllCops:
  Exclude:
    - bin/stubs/*
  TargetRubyVersion: 2.3

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
RSpec/NestedGroups:
  Max: 4
Style/EmptyMethod:
  EnforcedStyle: expanded
Style/StringLiterals:
  EnforcedStyle: double_quotes
