require: rubocop-rspec

AllCops:
  Exclude:
    - bin/stubs/*
    - lib/spid/saml2/idp_metadata_parser.rb
  TargetRubyVersion: 2.3

Layout/DotPosition:
  EnforcedStyle: trailing
Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
    - spid.gemspec
Metrics/LineLength:
  Exclude:
    - spid.gemspec
RSpec/DescribeClass:
  Exclude:
    - spec/integration/**/*.rb
    - spec/requests/**/*.rb
RSpec/FilePath:
  Exclude:
    - spec/integration/**/*.rb
    - spec/requests/**/*.rb
RSpec/MultipleExpectations:
  Max: 2
RSpec/NestedGroups:
  Enabled: false
RSpec/SubjectStub:
  Enabled: false
Style/EmptyMethod:
  EnforcedStyle: expanded
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/WordArray:
  EnforcedStyle: brackets
